version: '3'

volumes:
  foodgr_data:
  foodgr_static:
  foodgr_media:

services:
  db:
    env_file: .env
    image: postgres:13
    volumes:
      - foodgr_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - foodgr_media:/app/media
      - foodgr_static:/backend_static
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - foodgr_static:/frontend_static
  gateway:
    build: ./nginx/
    env_file: .env
    depends_on:
      - backend
    volumes:
      - foodgr_media:/app/media
      - foodgr_static:/staticfiles
    ports:
      - 80:80