# Generated by Django 3.2.3 on 2024-08-08 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20240808_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='short_link_id',
        ),
    ]
