# Generated by Django 3.2.3 on 2024-08-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_ingredientrecipe_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(db_index=True, help_text='Максимально допустимое число знаков - 256.', max_length=256, verbose_name='Название'),
        ),
    ]
