# Generated by Django 3.2.3 on 2024-08-11 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.SmallIntegerField(help_text='Колличество ингредиентов', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Колличество'),
        ),
    ]
