# Generated by Django 3.2.3 on 2024-08-11 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_ingredientrecipe_ingredient'),
        ('users_feature', '0003_shoppingcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_list_by_recipe', to='content.recipe'),
        ),
    ]
