# Generated by Django 3.2.3 on 2024-08-11 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_recipe_author'),
        ('users_feature', '0004_alter_favorite_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_list_by_recipe', to='content.recipe'),
        ),
    ]
