# Generated by Django 3.2.3 on 2024-08-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_feature', '0005_alter_shoppingcart_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('user',), 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ('user',), 'verbose_name': 'Добавлен в корзину', 'verbose_name_plural': 'Добавлены в корзину'},
        ),
        migrations.AlterModelOptions(
            name='subscribe',
            options={'ordering': ('user',), 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
