# General
LONG_STR_CUT_VALUE = 10

# Tag
TAG_NAME_MAX_LENGTH = 32
TAG_SLUG_MAX_LENGTH = 32

# Ingredient
INGREDIENT_NAME_MAX_LENGTH = 128
INGREDIENT_MEASUREMENT_UNIT_MAX_LENGTH = 128

# Recipe
RECIPE_NAME_MAX_LENGTH = 256
MIN_COOKING_TIME_VALUE = 1
MAX_COOKING_TIME_VALUE = 32700
MIN_INGREDIENTS_AMOUNT = 1
MAX_INGREDIENTS_AMOUNT = 32700  # Allmost max safe value.
