# Generated by Django 3.2.3 on 2024-08-08 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=64, verbose_name='Короткая ссылка')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.recipe', verbose_name='Рецепт')),
            ],
        ),
    ]
