# Generated by Django 3.2.3 on 2024-08-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_recipeshorturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link_id',
            field=models.CharField(default=1, max_length=16, verbose_name='Короткая ссылка'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RecipeShortUrl',
        ),
    ]
