# Generated by Django 3.2.3 on 2024-08-11 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodgramuser',
            options={'ordering': ('username',), 'verbose_name': ('Пользователь',), 'verbose_name_plural': 'Пользователи'},
        ),
    ]
