# Generated by Django 3.2.3 on 2024-08-12 13:53

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='subscribe_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_list_by_subscribe_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
