# Generated by Django 3.2.3 on 2024-08-13 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240812_2053'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscribe',
            unique_together={('user', 'subscribe_to')},
        ),
    ]
