# Generated by Django 3.2.3 on 2024-08-16 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20240815_1652'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='foodgramuser',
            managers=[
            ],
        ),
    ]
